name: Update Recipes JSON

on:
  push:
    paths:
      - 'recipes/**/*.pdf'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update recipes.json
        run: |
          recipes_file="recipes/recipes.json"
          
          # Create JSON structure if it doesn't exist
          if [ ! -f "$recipes_file" ]; then
            echo '{"categories": {}}' > $recipes_file
          fi
          
          jq '.' $recipes_file > tmp.json

          # Loop through recipe folders and PDFs
          for dir in recipes/*/; do
            [ -d "$dir" ] || continue
            category=$(basename "$dir")
            
            # Ensure category exists in JSON
            jq --arg cat "$category" \
               'if .categories[$cat] then . else .categories[$cat] = [] end' tmp.json > tmp2.json && mv tmp2.json tmp.json
            
            # Loop through PDFs
            for pdf in "$dir"*.pdf; do
              [ -f "$pdf" ] || continue
              filename=$(basename "$pdf")
              
              # Add recipe if not already listed
              jq --arg cat "$category" --arg file "$filename" \
                 'if (.categories[$cat] | index($file)) == null then .categories[$cat] += [$file] else . end' tmp.json > tmp2.json && mv tmp2.json tmp.json
            done
          done
          
          mv tmp.json $recipes_file

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add recipes/recipes.json
          git commit -m 'Auto-update recipes.json'
          git push
